import { Injectable } from '@angular/core';
import { Bike, FilterKey } from '../models/bike.model';

@Injectable({ providedIn: 'root' })
export class CatalogService {
  /** WhatsApp number — replace when ready */
  readonly waNumber = '96170000000';

  readonly bikes: Bike[] = [

    /* ════════════════════════════════════════════════════════
       HAOJUE
    ════════════════════════════════════════════════════════ */
    {
      slug:    'sr200',
      brand:   'haojue',
      model:   'SR200',
      type_en: 'Sport Naked',
      type_ar: 'رياضي',
      engine:  '200cc',
      power:   '18.5 HP',
      desc_en: 'A sporty commuter with sharp styling and a fuel-injected 200cc engine. Perfect balance of performance and daily usability.',
      desc_ar: 'دراجة رياضية للتنقل بتصميم حاد ومحرك 200cc بالحقن المباشر. توازن مثالي بين الأداء والاستخدام اليومي.',
      intro_en: 'Built for riders who want sport-bike attitude without the sport-bike price tag. The SR200 combines sharp angular bodywork with a punchy fuel-injected single, making it equally at home cutting through morning traffic or tackling weekend canyon runs.',
      intro_ar: 'مصممة للراكبين الذين يريدون روح الدراجة الرياضية بدون سعرها المرتفع. تجمع SR200 بين تصميم زاوي حاد ومحرك أحادي الأسطوانة قوي بحقن الوقود، مما يجعلها مثالية للتنقل اليومي ورحلات نهاية الأسبوع.',
      features_en: [
        'Fuel-injected 200cc single-cylinder engine',
        'All-LED lighting with twin-pod headlight',
        'Digital LCD instrument cluster',
        'Inverted USD front forks',
        'Petal-style disc brakes (front & rear)',
        'Combined Braking System (CBS)',
        'Aggressive sport-naked styling',
      ],
      features_ar: [
        'محرك أحادي الأسطوانة 200cc بحقن الوقود',
        'إضاءة LED بالكامل مع مصباح أمامي مزدوج',
        'لوحة قياس رقمية LCD',
        'شوكات أمامية مقلوبة USD',
        'مكابح قرصية بتلات (أمامية وخلفية)',
        'نظام الكبح المدمج (CBS)',
        'تصميم رياضي عدواني',
      ],
      specs: [
        { label_en: 'Engine Type',    label_ar: 'نوع المحرك',     value: '4-stroke, single-cylinder, SOHC' },
        { label_en: 'Displacement',   label_ar: 'سعة المحرك',     value: '199 cc' },
        { label_en: 'Max Power',      label_ar: 'الطاقة القصوى',   value: '18.5 HP @ 8500 rpm' },
        { label_en: 'Cooling',        label_ar: 'التبريد',         value: 'Oil-cooled' },
        { label_en: 'Transmission',   label_ar: 'ناقل الحركة',     value: '5-speed manual' },
        { label_en: 'Fuel System',    label_ar: 'نظام الوقود',     value: 'Electronic Fuel Injection' },
        { label_en: 'Fuel Capacity',  label_ar: 'سعة الخزان',      value: '15.0 L' },
        { label_en: 'Seat Height',    label_ar: 'ارتفاع المقعد',   value: '790 mm' },
        { label_en: 'Curb Weight',    label_ar: 'الوزن',          value: '143 kg' },
        { label_en: 'Front Brake',    label_ar: 'المكبح الأمامي',  value: '276 mm disc, hydraulic' },
        { label_en: 'Rear Brake',     label_ar: 'المكبح الخلفي',   value: '220 mm disc, hydraulic' },
        { label_en: 'Tires (F / R)',  label_ar: 'الإطارات',        value: '100/80-17 / 130/70-17' },
      ],
      emoji: '🏍️',
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&h=400&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1547549082-6bc09f2049ae?auto=format&fit=crop&w=900&h=600&q=85',
      ],
    },

    {
      slug:    'hj150-3',
      brand:   'haojue',
      model:   'HJ150-3',
      type_en: 'Commuter',
      type_ar: 'تنقل يومي',
      engine:  '150cc',
      power:   '12 HP',
      desc_en: 'Reliable, fuel-efficient daily commuter. Low maintenance costs and proven Honda-sourced engine technology.',
      desc_ar: 'دراجة موثوقة وموفرة للوقود للاستخدام اليومي. تكاليف صيانة منخفضة وتقنية محرك مستمدة من هوندا.',
      intro_en: 'The reliable workhorse that built Haojue\'s reputation in Lebanon. Engineered for daily-driver duty with low maintenance costs, exceptional fuel economy, and Honda-licensed engine technology proven across millions of miles in markets worldwide.',
      intro_ar: 'الدراجة الموثوقة التي بنت سمعة هاوجيو في لبنان. مصممة للاستخدام اليومي مع تكاليف صيانة منخفضة، اقتصاد ممتاز في الوقود، وتقنية محرك مرخصة من هوندا أثبتت جدارتها في الأسواق العالمية.',
      features_en: [
        'Honda-licensed 150cc engine technology',
        'Exceptional 45+ km/L fuel economy',
        'Low-maintenance carburettor system',
        'Comfortable upright commuter ergonomics',
        'Generous fuel tank for long range',
        'Robust tubular steel frame',
        'Tubeless tires standard',
      ],
      features_ar: [
        'تقنية محرك 150cc مرخصة من هوندا',
        'اقتصاد ممتاز في الوقود +45 كم/لتر',
        'نظام مغذي منخفض الصيانة',
        'وضعية ركوب مريحة للتنقل اليومي',
        'خزان وقود واسع لمدى طويل',
        'هيكل فولاذي أنبوبي قوي',
        'إطارات بدون أنبوب قياسية',
      ],
      specs: [
        { label_en: 'Engine Type',    label_ar: 'نوع المحرك',     value: '4-stroke, single-cylinder' },
        { label_en: 'Displacement',   label_ar: 'سعة المحرك',     value: '149 cc' },
        { label_en: 'Max Power',      label_ar: 'الطاقة القصوى',   value: '12 HP @ 7500 rpm' },
        { label_en: 'Cooling',        label_ar: 'التبريد',         value: 'Air-cooled' },
        { label_en: 'Transmission',   label_ar: 'ناقل الحركة',     value: '5-speed manual' },
        { label_en: 'Fuel System',    label_ar: 'نظام الوقود',     value: 'Carburettor' },
        { label_en: 'Fuel Capacity',  label_ar: 'سعة الخزان',      value: '14.0 L' },
        { label_en: 'Seat Height',    label_ar: 'ارتفاع المقعد',   value: '770 mm' },
        { label_en: 'Curb Weight',    label_ar: 'الوزن',          value: '128 kg' },
        { label_en: 'Front Brake',    label_ar: 'المكبح الأمامي',  value: '240 mm disc' },
        { label_en: 'Rear Brake',     label_ar: 'المكبح الخلفي',   value: '130 mm drum' },
        { label_en: 'Tires (F / R)',  label_ar: 'الإطارات',        value: '2.75-18 / 3.00-18' },
      ],
      emoji: '🛵',
      image: 'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?auto=format&fit=crop&w=600&h=400&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1508357710528-af67af14c1b9?auto=format&fit=crop&w=900&h=600&q=85',
      ],
    },

    {
      slug:    'dr160s',
      brand:   'haojue',
      model:   'DR160S',
      type_en: 'Street Naked',
      type_ar: 'ناكيد',
      engine:  '160cc',
      power:   '15 HP',
      desc_en: 'Aggressive street naked with muscular lines and a punchy 160cc single. Turns heads on every street.',
      desc_ar: 'دراجة ناكيد عدوانية بخطوط عضلية ومحرك 160cc قوي. تلفت الأنظار في كل شارع.',
      intro_en: 'A street naked that punches well above its displacement. Aggressive muscular bodywork wraps a torquey 160cc single, with sport-inspired ergonomics that make every commute feel like a ride. Designed to be seen and heard.',
      intro_ar: 'دراجة ناكيد للشوارع تتفوق على سعة محركها. هيكل عضلي عدواني يحيط بمحرك 160cc قوي، مع وضعية ركوب مستوحاة من الرياضية تجعل كل رحلة تنقل تشعر وكأنها مغامرة. مصممة لتُرى وتُسمع.',
      features_en: [
        '160cc air-cooled single-cylinder',
        'Inverted front forks for sharp handling',
        'Twin-pod LED headlight',
        'Digital tachometer and speedometer',
        'Sport-style fuel tank with knee pads',
        'Wider 130mm rear tire',
        'Dual-disc brake system with CBS',
      ],
      features_ar: [
        'محرك أحادي 160cc مبرد بالهواء',
        'شوكات أمامية مقلوبة لقيادة حادة',
        'مصباح أمامي مزدوج LED',
        'عداد رقمي للسرعة ودوران المحرك',
        'خزان وقود رياضي مع وسائد للركبة',
        'إطار خلفي أعرض 130 ملم',
        'نظام كبح مزدوج بالقرص مع CBS',
      ],
      specs: [
        { label_en: 'Engine Type',    label_ar: 'نوع المحرك',     value: '4-stroke, single-cylinder, SOHC' },
        { label_en: 'Displacement',   label_ar: 'سعة المحرك',     value: '162 cc' },
        { label_en: 'Max Power',      label_ar: 'الطاقة القصوى',   value: '15 HP @ 8500 rpm' },
        { label_en: 'Cooling',        label_ar: 'التبريد',         value: 'Air-cooled' },
        { label_en: 'Transmission',   label_ar: 'ناقل الحركة',     value: '5-speed manual' },
        { label_en: 'Fuel System',    label_ar: 'نظام الوقود',     value: 'Carburettor' },
        { label_en: 'Fuel Capacity',  label_ar: 'سعة الخزان',      value: '12.0 L' },
        { label_en: 'Seat Height',    label_ar: 'ارتفاع المقعد',   value: '800 mm' },
        { label_en: 'Curb Weight',    label_ar: 'الوزن',          value: '135 kg' },
        { label_en: 'Front Brake',    label_ar: 'المكبح الأمامي',  value: '276 mm disc' },
        { label_en: 'Rear Brake',     label_ar: 'المكبح الخلفي',   value: '220 mm disc' },
        { label_en: 'Tires (F / R)',  label_ar: 'الإطارات',        value: '100/80-17 / 130/70-17' },
      ],
      emoji: '🏍️',
      image: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?auto=format&fit=crop&w=600&h=400&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1609630875171-b1321377ee65?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&h=600&q=85',
      ],
    },

    /* ════════════════════════════════════════════════════════
       ZONTES
    ════════════════════════════════════════════════════════ */
    {
      slug:    'zt310-r',
      brand:   'zontes',
      model:   'ZT310-R',
      type_en: 'Sport',
      type_ar: 'رياضي',
      engine:  '310cc',
      power:   '35 HP',
      desc_en: 'Full-fairing sport bike with liquid-cooled 310cc engine, TFT display, and traction control. A serious machine.',
      desc_ar: 'دراجة رياضية بهيكل كامل ومحرك 310cc مبرد بالسائل وشاشة TFT وتحكم في الجر. آلة جدية.',
      intro_en: 'The benchmark for sub-400cc sportbikes. Full aerodynamic fairings wrap a liquid-cooled 310cc DOHC single, and the electronics package — TFT dashboard, three ride modes, traction control, and cornering ABS — typically belongs on bikes twice the price.',
      intro_ar: 'المرجع في دراجات السباق تحت 400cc. هياكل ديناميكية كاملة تحيط بمحرك أحادي 310cc DOHC مبرد بالسائل، وحزمة إلكترونيات — شاشة TFT، ثلاثة أوضاع قيادة، تحكم في الجر، و ABS للمنعطفات — تنتمي عادة لدراجات بضعف السعر.',
      features_en: [
        'Liquid-cooled 310cc DOHC single-cylinder',
        '5-inch full-colour TFT dashboard',
        'Three switchable ride modes (Sport / Street / Rain)',
        'Traction Control System (TCS)',
        'Cornering ABS via IMU',
        'Aluminium swingarm',
        'Bosch fuel injection',
        'LED Matrix headlight',
      ],
      features_ar: [
        'محرك أحادي 310cc DOHC مبرد بالسائل',
        'شاشة TFT ملونة 5 بوصة',
        'ثلاثة أوضاع قيادة (رياضي/شارع/مطر)',
        'نظام التحكم في الجر (TCS)',
        'ABS للمنعطفات عبر IMU',
        'ذراع متأرجح من الألمنيوم',
        'حقن وقود من بوش',
        'مصباح أمامي LED Matrix',
      ],
      specs: [
        { label_en: 'Engine Type',    label_ar: 'نوع المحرك',     value: 'Liquid-cooled, DOHC, single-cylinder' },
        { label_en: 'Displacement',   label_ar: 'سعة المحرك',     value: '312 cc' },
        { label_en: 'Max Power',      label_ar: 'الطاقة القصوى',   value: '35 HP @ 9500 rpm' },
        { label_en: 'Max Torque',     label_ar: 'العزم الأقصى',    value: '30 Nm @ 7500 rpm' },
        { label_en: 'Transmission',   label_ar: 'ناقل الحركة',     value: '6-speed manual w/ slipper clutch' },
        { label_en: 'Fuel System',    label_ar: 'نظام الوقود',     value: 'Bosch EFI' },
        { label_en: 'Fuel Capacity',  label_ar: 'سعة الخزان',      value: '14.5 L' },
        { label_en: 'Seat Height',    label_ar: 'ارتفاع المقعد',   value: '795 mm' },
        { label_en: 'Curb Weight',    label_ar: 'الوزن',          value: '163 kg' },
        { label_en: 'Front Brake',    label_ar: 'المكبح الأمامي',  value: '300 mm disc, 4-piston' },
        { label_en: 'Rear Brake',     label_ar: 'المكبح الخلفي',   value: '230 mm disc, single-piston' },
        { label_en: 'Tires (F / R)',  label_ar: 'الإطارات',        value: '110/70-17 / 150/60-17' },
      ],
      emoji: '🏎️',
      image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=600&h=400&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&h=600&q=85',
      ],
    },

    {
      slug:    'zt310-t',
      brand:   'zontes',
      model:   'ZT310-T',
      type_en: 'Naked',
      type_ar: 'ناكيد',
      engine:  '310cc',
      power:   '34 HP',
      desc_en: 'Aggressive naked streetfighter. Same punchy 310cc heart, ride modes, cornering ABS, and a bold standout look.',
      desc_ar: 'دراجة ناكيد عدوانية. نفس محرك 310cc القوي مع أوضاع القيادة وـABS للتعرجات وتصميم بارز.',
      intro_en: 'Strip away the bodywork, keep the soul. The ZT310-T takes the same liquid-cooled 310cc heart as the R model and wraps it in aggressive naked streetfighter styling, with a more upright riding position that\'s perfect for city use without giving up the performance.',
      intro_ar: 'انزع الهيكل، احتفظ بالروح. تأخذ ZT310-T نفس محرك 310cc المبرد بالسائل من نموذج R وتغلفه بتصميم ناكيد عدواني، مع وضعية ركوب مستقيمة أكثر مثالية للمدينة دون التضحية بالأداء.',
      features_en: [
        'Same 310cc liquid-cooled engine as ZT310-R',
        'Streetfighter naked styling',
        'More upright commuter-friendly ergonomics',
        '5-inch TFT colour dashboard',
        'Three ride modes and TCS',
        'Cornering ABS',
        'Full LED lighting',
        'Adjustable suspension front & rear',
      ],
      features_ar: [
        'نفس محرك 310cc مبرد بالسائل من ZT310-R',
        'تصميم ناكيد عدواني',
        'وضعية ركوب أكثر استقامة',
        'شاشة TFT ملونة 5 بوصة',
        'ثلاثة أوضاع قيادة و TCS',
        'ABS للمنعطفات',
        'إضاءة LED كاملة',
        'تعليق قابل للتعديل أمامي وخلفي',
      ],
      specs: [
        { label_en: 'Engine Type',    label_ar: 'نوع المحرك',     value: 'Liquid-cooled, DOHC, single-cylinder' },
        { label_en: 'Displacement',   label_ar: 'سعة المحرك',     value: '312 cc' },
        { label_en: 'Max Power',      label_ar: 'الطاقة القصوى',   value: '34 HP @ 9500 rpm' },
        { label_en: 'Max Torque',     label_ar: 'العزم الأقصى',    value: '30 Nm @ 7000 rpm' },
        { label_en: 'Transmission',   label_ar: 'ناقل الحركة',     value: '6-speed manual w/ slipper clutch' },
        { label_en: 'Fuel System',    label_ar: 'نظام الوقود',     value: 'Bosch EFI' },
        { label_en: 'Fuel Capacity',  label_ar: 'سعة الخزان',      value: '14.5 L' },
        { label_en: 'Seat Height',    label_ar: 'ارتفاع المقعد',   value: '810 mm' },
        { label_en: 'Curb Weight',    label_ar: 'الوزن',          value: '158 kg' },
        { label_en: 'Front Brake',    label_ar: 'المكبح الأمامي',  value: '300 mm disc, 4-piston' },
        { label_en: 'Rear Brake',     label_ar: 'المكبح الخلفي',   value: '230 mm disc' },
        { label_en: 'Tires (F / R)',  label_ar: 'الإطارات',        value: '110/70-17 / 150/60-17' },
      ],
      emoji: '🏍️',
      image: 'https://images.unsplash.com/photo-1547549082-6bc09f2049ae?auto=format&fit=crop&w=600&h=400&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1547549082-6bc09f2049ae?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1609630875171-b1321377ee65?auto=format&fit=crop&w=900&h=600&q=85',
      ],
    },

    {
      slug:    'zt155-u1',
      brand:   'zontes',
      model:   'ZT155-U1',
      type_en: 'Scooter',
      type_ar: 'سكوتر',
      engine:  '155cc',
      power:   '14 HP',
      desc_en: 'Premium urban scooter with smart keyless ignition, TFT dash, USB charging, and large underseat storage.',
      desc_ar: 'سكوتر حضري فاخر مع إشعال ذكي بدون مفتاح وشاشة TFT وشحن USB وتخزين واسع تحت المقعد.',
      intro_en: 'Premium scootering, redefined. The U1 borrows technology straight from Zontes\' flagship motorcycles — smart keyless ignition, a full-colour TFT dashboard, USB charging on the dash, and an underseat compartment large enough for a full-face helmet.',
      intro_ar: 'سكوترة فاخرة، معاد تعريفها. تستعير U1 التقنية مباشرة من دراجات زونتيس الرائدة — إشعال ذكي بدون مفتاح، شاشة TFT ملونة كاملة، شحن USB على لوحة القيادة، ومقصورة تحت المقعد كبيرة بما يكفي لخوذة كاملة.',
      features_en: [
        'Smart keyless ignition system',
        'Full-colour TFT dashboard',
        'USB charging port',
        'Underseat storage (fits full-face helmet)',
        'LED lighting throughout',
        'Liquid-cooled 155cc engine',
        '14-inch wheels for highway stability',
        'Disc brakes both ends with ABS',
      ],
      features_ar: [
        'نظام إشعال ذكي بدون مفتاح',
        'شاشة TFT ملونة كاملة',
        'منفذ شحن USB',
        'تخزين تحت المقعد (يتسع لخوذة كاملة)',
        'إضاءة LED بالكامل',
        'محرك 155cc مبرد بالسائل',
        'عجلات 14 بوصة لاستقرار الطريق السريع',
        'مكابح قرصية في الطرفين مع ABS',
      ],
      specs: [
        { label_en: 'Engine Type',    label_ar: 'نوع المحرك',     value: 'Liquid-cooled, single-cylinder' },
        { label_en: 'Displacement',   label_ar: 'سعة المحرك',     value: '155 cc' },
        { label_en: 'Max Power',      label_ar: 'الطاقة القصوى',   value: '14 HP @ 8500 rpm' },
        { label_en: 'Transmission',   label_ar: 'ناقل الحركة',     value: 'CVT automatic' },
        { label_en: 'Fuel System',    label_ar: 'نظام الوقود',     value: 'Electronic Fuel Injection' },
        { label_en: 'Fuel Capacity',  label_ar: 'سعة الخزان',      value: '7.5 L' },
        { label_en: 'Seat Height',    label_ar: 'ارتفاع المقعد',   value: '780 mm' },
        { label_en: 'Curb Weight',    label_ar: 'الوزن',          value: '138 kg' },
        { label_en: 'Front Brake',    label_ar: 'المكبح الأمامي',  value: '260 mm disc, ABS' },
        { label_en: 'Rear Brake',     label_ar: 'المكبح الخلفي',   value: '240 mm disc, ABS' },
        { label_en: 'Wheels',         label_ar: 'العجلات',         value: '14-inch alloy front & rear' },
      ],
      emoji: '🛵',
      image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?auto=format&fit=crop&w=600&h=400&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1617654112368-307921291f42?auto=format&fit=crop&w=900&h=600&q=85',
      ],
    },

    {
      slug:    'zt125-u',
      brand:   'zontes',
      model:   'ZT125-U',
      type_en: 'Scooter',
      type_ar: 'سكوتر',
      engine:  '125cc',
      power:   '11 HP',
      desc_en: 'Entry-level scooter for beginners and city riders. Excellent fuel economy and easy maneuverability.',
      desc_ar: 'سكوتر للمبتدئين وراكبي المدينة. اقتصاد ممتاز في الوقود وسهولة مناورة.',
      intro_en: 'An honest, easy-to-ride scooter at a price that makes sense. Designed for new riders and city commuters, the ZT125-U focuses on the essentials — light weight, easy handling, and the kind of bulletproof reliability that makes a scooter a true everyday tool.',
      intro_ar: 'سكوترة صادقة وسهلة القيادة بسعر منطقي. مصممة للراكبين الجدد وسكان المدن، تركز ZT125-U على الأساسيات — وزن خفيف، تعامل سهل، وموثوقية تجعل السكوترة أداة يومية حقيقية.',
      features_en: [
        'Lightweight 125cc 4-stroke engine',
        'Step-through ergonomics',
        'LED daytime running light',
        'Digital LCD instruments',
        'Generous underseat storage',
        'Low 760 mm seat height — beginner-friendly',
        'Tubeless tires for easier repairs',
        'Push-button electric start',
      ],
      features_ar: [
        'محرك خفيف 125cc 4 أشواط',
        'تصميم Step-through',
        'إضاءة نهارية LED',
        'لوحة قياس رقمية LCD',
        'تخزين واسع تحت المقعد',
        'ارتفاع مقعد منخفض 760 ملم — مناسب للمبتدئين',
        'إطارات بدون أنبوب لإصلاح أسهل',
        'تشغيل كهربائي بضغطة زر',
      ],
      specs: [
        { label_en: 'Engine Type',    label_ar: 'نوع المحرك',     value: 'Air-cooled, single-cylinder, 4-stroke' },
        { label_en: 'Displacement',   label_ar: 'سعة المحرك',     value: '125 cc' },
        { label_en: 'Max Power',      label_ar: 'الطاقة القصوى',   value: '11 HP @ 8000 rpm' },
        { label_en: 'Transmission',   label_ar: 'ناقل الحركة',     value: 'CVT automatic' },
        { label_en: 'Fuel System',    label_ar: 'نظام الوقود',     value: 'Electronic Fuel Injection' },
        { label_en: 'Fuel Capacity',  label_ar: 'سعة الخزان',      value: '6.5 L' },
        { label_en: 'Seat Height',    label_ar: 'ارتفاع المقعد',   value: '760 mm' },
        { label_en: 'Curb Weight',    label_ar: 'الوزن',          value: '115 kg' },
        { label_en: 'Front Brake',    label_ar: 'المكبح الأمامي',  value: '240 mm disc' },
        { label_en: 'Rear Brake',     label_ar: 'المكبح الخلفي',   value: '130 mm drum' },
        { label_en: 'Wheels',         label_ar: 'العجلات',         value: '12-inch alloy front & rear' },
      ],
      emoji: '🛵',
      image: 'https://images.unsplash.com/photo-1596443686812-2f45229eebc3?auto=format&fit=crop&w=600&h=400&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1596443686812-2f45229eebc3?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1617654112368-307921291f42?auto=format&fit=crop&w=900&h=600&q=85',
      ],
    },

    /* ════════════════════════════════════════════════════════
       LINHAI
    ════════════════════════════════════════════════════════ */
    {
      slug:    'lh150t-6',
      brand:   'linhai',
      model:   'LH150T-6',
      type_en: 'Scooter',
      type_ar: 'سكوتر',
      engine:  '150cc',
      power:   '10 HP',
      desc_en: 'Practical and affordable scooter built for everyday urban transport. Easy to ride and park.',
      desc_ar: 'سكوتر عملي بسعر مناسب مصمم للتنقل الحضري اليومي. سهل الركوب والإيقاف.',
      intro_en: 'Practical Lebanese urban transport at its most accessible. The LH150T-6 strips away the gimmicks and focuses on what matters: a reliable engine, easy maintenance, parking that fits anywhere, and total cost of ownership that beats anything on four wheels.',
      intro_ar: 'النقل الحضري اللبناني العملي في أبسط أشكاله. تتخلص LH150T-6 من الزخارف وتركز على ما يهم: محرك موثوق، صيانة سهلة، إيقاف يناسب أي مكان، وتكلفة ملكية إجمالية تتفوق على أي مركبة بأربع عجلات.',
      features_en: [
        'Air-cooled 150cc 4-stroke engine',
        'Light and easy to manoeuvre',
        'Wide rear seat for passenger comfort',
        'Underseat storage compartment',
        'Strong centre stand',
        'Tubeless tires',
        'Affordable parts and service network',
      ],
      features_ar: [
        'محرك 150cc 4 أشواط مبرد بالهواء',
        'خفيف وسهل المناورة',
        'مقعد خلفي عريض لراحة الراكب',
        'مقصورة تخزين تحت المقعد',
        'دعامة مركزية قوية',
        'إطارات بدون أنبوب',
        'قطع غيار وخدمة بأسعار معقولة',
      ],
      specs: [
        { label_en: 'Engine Type',    label_ar: 'نوع المحرك',     value: 'Air-cooled, single-cylinder, 4-stroke' },
        { label_en: 'Displacement',   label_ar: 'سعة المحرك',     value: '149 cc' },
        { label_en: 'Max Power',      label_ar: 'الطاقة القصوى',   value: '10 HP @ 7500 rpm' },
        { label_en: 'Transmission',   label_ar: 'ناقل الحركة',     value: 'CVT automatic' },
        { label_en: 'Fuel System',    label_ar: 'نظام الوقود',     value: 'Carburettor' },
        { label_en: 'Fuel Capacity',  label_ar: 'سعة الخزان',      value: '7.0 L' },
        { label_en: 'Seat Height',    label_ar: 'ارتفاع المقعد',   value: '770 mm' },
        { label_en: 'Curb Weight',    label_ar: 'الوزن',          value: '120 kg' },
        { label_en: 'Front Brake',    label_ar: 'المكبح الأمامي',  value: '220 mm disc' },
        { label_en: 'Rear Brake',     label_ar: 'المكبح الخلفي',   value: '130 mm drum' },
        { label_en: 'Wheels',         label_ar: 'العجلات',         value: '12-inch front & rear' },
      ],
      emoji: '🛵',
      image: 'https://images.unsplash.com/photo-1617654112368-307921291f42?auto=format&fit=crop&w=600&h=400&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1617654112368-307921291f42?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1596443686812-2f45229eebc3?auto=format&fit=crop&w=900&h=600&q=85',
      ],
    },

    {
      slug:    'lh250-3a',
      brand:   'linhai',
      model:   'LH250-3A',
      type_en: 'Motorcycle',
      type_ar: 'دراجة نارية',
      engine:  '250cc',
      power:   '22 HP',
      desc_en: 'Versatile mid-size bike for city and open road alike. Comfortable upright riding position.',
      desc_ar: 'دراجة متعددة الاستخدام متوسطة الحجم مناسبة للمدينة والطريق المفتوح. وضعية ركوب مريحة.',
      intro_en: 'When the city\'s not enough. The LH250-3A is built for riders who split time between urban commutes and weekend exploration — a versatile 250cc mid-size with comfortable upright ergonomics and the range to actually go somewhere.',
      intro_ar: 'عندما لا تكون المدينة كافية. مصممة LH250-3A للراكبين الذين يقسمون وقتهم بين التنقل الحضري واستكشاف نهاية الأسبوع — دراجة متوسطة الحجم 250cc متعددة الاستخدامات بوضعية ركوب مريحة ومدى يأخذك بعيداً.',
      features_en: [
        '250cc 4-stroke air-cooled engine',
        'Versatile upright riding position',
        '5-speed manual transmission',
        'Twin-piston front brake caliper',
        'Spoke wheels with tubed tires',
        'Generous 18 L fuel tank',
        'Designed for Lebanese road conditions',
      ],
      features_ar: [
        'محرك 250cc 4 أشواط مبرد بالهواء',
        'وضعية ركوب مستقيمة متعددة الاستخدامات',
        'ناقل حركة يدوي 5 سرعات',
        'مكبح أمامي بمكبسين',
        'عجلات بأسلاك بإطارات بأنبوب',
        'خزان وقود واسع 18 لتر',
        'مصممة لظروف الطرق اللبنانية',
      ],
      specs: [
        { label_en: 'Engine Type',    label_ar: 'نوع المحرك',     value: 'Air-cooled, single-cylinder, 4-stroke' },
        { label_en: 'Displacement',   label_ar: 'سعة المحرك',     value: '249 cc' },
        { label_en: 'Max Power',      label_ar: 'الطاقة القصوى',   value: '22 HP @ 8500 rpm' },
        { label_en: 'Transmission',   label_ar: 'ناقل الحركة',     value: '5-speed manual' },
        { label_en: 'Fuel System',    label_ar: 'نظام الوقود',     value: 'Carburettor' },
        { label_en: 'Fuel Capacity',  label_ar: 'سعة الخزان',      value: '18.0 L' },
        { label_en: 'Seat Height',    label_ar: 'ارتفاع المقعد',   value: '810 mm' },
        { label_en: 'Curb Weight',    label_ar: 'الوزن',          value: '160 kg' },
        { label_en: 'Front Brake',    label_ar: 'المكبح الأمامي',  value: '280 mm disc, 2-piston' },
        { label_en: 'Rear Brake',     label_ar: 'المكبح الخلفي',   value: '220 mm disc' },
        { label_en: 'Tires (F / R)',  label_ar: 'الإطارات',        value: '3.00-19 / 4.10-18' },
      ],
      emoji: '🏍️',
      image: 'https://images.unsplash.com/photo-1508357710528-af67af14c1b9?auto=format&fit=crop&w=600&h=400&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1508357710528-af67af14c1b9?auto=format&fit=crop&w=900&h=600&q=85',
        'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?auto=format&fit=crop&w=900&h=600&q=85',
      ],
    },

    {
      slug:    'lh400-atv',
      brand:   'linhai',
      model:   'LH400 ATV',
      type_en: 'ATV',
      type_ar: 'رباعية العجلات',
      engine:  '400cc',
      power:   '28 HP',
      desc_en: 'Powerful all-terrain quad for off-road adventure, farming, and utility work. Built tough.',
      desc_ar: 'رباعية عجلات قوية للمغامرات خارج الطريق والزراعة والأعمال العامة. مبنية بمتانة.',
      intro_en: 'A serious work-and-play machine. Whether you need to haul through orchards, traverse mountain trails, or just have fun off-road, the LH400 ATV delivers 28 HP of torquey power with selectable 2WD/4WD and a load capacity built for real work.',
      intro_ar: 'آلة جدية للعمل واللعب. سواء كنت بحاجة إلى السحب عبر البساتين، عبور مسارات الجبال، أو الاستمتاع خارج الطريق، تقدم LH400 ATV قوة 28 حصاناً مع 2WD/4WD قابل للاختيار وقدرة حمولة مبنية للعمل الحقيقي.',
      features_en: [
        '400cc liquid-cooled 4-stroke engine',
        'Selectable 2WD / 4WD with differential lock',
        'CVT automatic transmission with reverse',
        'Independent A-arm suspension front & rear',
        'Front cargo rack (40 kg capacity)',
        'Rear cargo rack (80 kg capacity)',
        'Hydraulic disc brakes all-around',
        '12-inch alloy wheels with knobby tires',
      ],
      features_ar: [
        'محرك 400cc 4 أشواط مبرد بالسائل',
        'دفع 2WD / 4WD قابل للاختيار مع قفل تفاضلي',
        'ناقل حركة CVT تلقائي مع رجوع',
        'تعليق ذراع A مستقل أمامي وخلفي',
        'حامل أمتعة أمامي (40 كجم)',
        'حامل أمتعة خلفي (80 كجم)',
        'مكابح قرصية هيدروليكية في كل مكان',
        'عجلات ألمنيوم 12 بوصة بإطارات وعرة',
      ],
      specs: [
        { label_en: 'Engine Type',     label_ar: 'نوع المحرك',     value: 'Liquid-cooled, single-cylinder, 4-stroke' },
        { label_en: 'Displacement',    label_ar: 'سعة المحرك',     value: '400 cc' },
        { label_en: 'Max Power',       label_ar: 'الطاقة القصوى',   value: '28 HP @ 7000 rpm' },
        { label_en: 'Drivetrain',      label_ar: 'نظام الدفع',      value: 'Selectable 2WD / 4WD / Diff-lock' },
        { label_en: 'Transmission',    label_ar: 'ناقل الحركة',     value: 'CVT automatic with reverse' },
        { label_en: 'Fuel Capacity',   label_ar: 'سعة الخزان',      value: '15.0 L' },
        { label_en: 'Length × Width',  label_ar: 'الطول × العرض',   value: '2120 × 1180 mm' },
        { label_en: 'Ground Clearance',label_ar: 'الخلوص الأرضي',  value: '275 mm' },
        { label_en: 'Front Rack',      label_ar: 'الحامل الأمامي',  value: '40 kg capacity' },
        { label_en: 'Rear Rack',       label_ar: 'الحامل الخلفي',   value: '80 kg capacity' },
        { label_en: 'Brakes',          label_ar: 'المكابح',         value: 'Hydraulic disc, front & rear' },
        { label_en: 'Tires',           label_ar: 'الإطارات',        value: '12-inch alloy, knobby tread' },
      ],
      emoji: '🚜',
      image: 'https://images.unsplash.com/photo-1622185135505-2d795003994a?auto=format&fit=crop&w=600&h=400&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1622185135505-2d795003994a?auto=format&fit=crop&w=900&h=600&q=85',
      ],
    },
  ];

  filter(key: FilterKey) {
    return key === 'all'
      ? this.bikes
      : this.bikes.filter((b) => b.brand === key);
  }

  getBySlug(slug: string) {
    return this.bikes.find((b) => b.slug === slug);
  }
}
