import { IsEnum, IsOptional, IsString } from 'class-validator';
import { EventType } from '@prisma/client';

export class TrackEventDto {
  /** The bike this event belongs to (optional — some events have no bike context) */
  @IsOptional()
  @IsString()
  bikeId?: string;

  /** Alternative to bikeId — the client may know the slug but not the id */
  @IsOptional()
  @IsString()
  slug?: string;

  @IsEnum(EventType)
  event: EventType;

  @IsOptional()
  @IsString()
  lang?: string;

  /** Anonymous session token generated by the client */
  @IsOptional()
  @IsString()
  sessionId?: string;
}
